#include "NDItk/multigroup/AverageFissionEnergyRelease.hpp"
#include "NDItk/multigroup/CrossSection.hpp"
#include "NDItk/multigroup/EnergyGroupStructure.hpp"
#include "NDItk/multigroup/FissionNeutronMultiplicity.hpp"
#include "NDItk/multigroup/FissionNeutronProduction.hpp"
#include "NDItk/multigroup/FluxWeights.hpp"
#include "NDItk/multigroup/HeatingNumbers.hpp"
#include "NDItk/multigroup/Kerma.hpp"
#include "NDItk/multigroup/LegendreMoment.hpp"
#include "NDItk/multigroup/Metadata.hpp"
#include "NDItk/multigroup/OutgoingParticleTransportData.hpp"
#include "NDItk/multigroup/OutgoingParticleTypes.hpp"
#include "NDItk/multigroup/ReactionCrossSections.hpp"
#include "NDItk/multigroup/ScatteringMatrix.hpp"
#include "NDItk/multigroup/TotalCrossSection.hpp"
#include "NDItk/multigroup/Velocities.hpp"

#include "NDItk/depletion/Multiplicities.hpp"
#include "NDItk/depletion/ReactionMultiplicities.hpp"
#include "NDItk/depletion/ReactionMultiplicityType.hpp"
#include "NDItk/depletion/Product.hpp"

#include "NDItk/MultigroupTable.hpp"
